import { Injectable } from '@nestjs/common';
import { IseService } from '../ise/ise.service';
import * as moment from 'moment';
import { CreateGuestUserDto } from 'src/models/CreateGuestUserDto.dto';
import { GuestInfo } from 'src/models/GuestInfo';
import { GuestUser } from 'src/models/GuestUser';
import { IseGuestUserDto } from 'src/models/IseGuestUserDto';
import { GuestAccessInfo } from 'src/models/GuestAccessInfo';
import { InjectModel } from '@nestjs/mongoose';
import { GuestUserMongoose } from 'src/models/GuestUserMongoose';
import { Model } from 'mongoose';
import { BehaviorSubject } from 'rxjs';

const LOCATION = 'Brussels';
const PORTAL_ID = 'f10871e0-7159-11e7-a355-005056aba474';
const GUEST_TYPE = 'Weekly (default)'; // TODO: check guest type
const MOMENT_FORMAT = 'MM/DD/YYYY HH:mm';
const DAY = 'day';

@Injectable()
export class GuestUserService {
  private VALID_DAYS: number;
  public guestUsers$: BehaviorSubject<GuestUserMongoose[]>;

  constructor(
    private iseService: IseService,
    @InjectModel('GuestUser') private guestUserModel: Model<GuestUserMongoose>,
  ) {
    this.VALID_DAYS = 2;
    this.initGuestUsers$();
  }

  private async initGuestUsers$() {
    try {
      this.guestUsers$ = new BehaviorSubject(await this.getAllGuestUsers());
    } catch (error) {
      console.log(error);
    }
  }

  public async createGuestUser(createGuestUserDto: CreateGuestUserDto) {
    const {
      password,
      firstName,
      surName,
      emailAddress,
      personBeingVisited,
      reasonForVisit,
    } = createGuestUserDto;

    const guestInfo: GuestInfo = this.generateGuestInfo(
      firstName,
      surName,
      password,
      emailAddress,
    );
    const guestUser: GuestUser = this.generateGuestUser(
      guestInfo,
      personBeingVisited,
      reasonForVisit,
    );
    const iseGuestUserDto: IseGuestUserDto = {
      GuestUser: guestUser,
    };
    try {
      //  await this.iseService.createISEGuestUser(iseGuestUserDto);
      const guestUserMongoose = this.createGuestUserMongoose(guestUser);
      const guestUserModel = await this.createGuestUserModel(guestUserMongoose);
      this.saveGuestUserModelToMongodb(guestUserModel);
      this.guestUsers$.next(
        this.addGuestUserModelToGuestUsers$(guestUserMongoose),
      );
    } catch (error) {
      console.log(error);
      console.log(`could not create Ise guest user ${error}`);
    }
  }

  private addGuestUserModelToGuestUsers$(
    guestUserMongoose: GuestUserMongoose,
  ): GuestUserMongoose[] {
    try {
      const guestUserModels = this.guestUsers$.value;
      guestUserModels.push(guestUserMongoose);
      return guestUserModels;
    } catch (error) {}
  }

  private removeGuestUserModelFromGuestUsers$(
    guestUserMongoose: GuestUserMongoose,
  ) {
    // implement
  }

  private async getAllGuestUsers(): Promise<GuestUserMongoose[]> {
    let guestUsers: GuestUserMongoose[] = [];
    this.guestUserModel.find({}, (err, docs) => {
      guestUsers = docs as GuestUserMongoose[];
    });
    return guestUsers;
  }

  // refactor

  private async saveGuestUserModelToMongodb(
    guestUserModel: Model<GuestUserMongoose>,
  ): Promise<void> {
    try {
      await guestUserModel.save();
    } catch (error) {
      console.log(error);
    }
  }

  private createGuestUserMongoose(guestUser: GuestUser): GuestUserMongoose {
    try {
      const { personBeingVisited } = guestUser;
      const { fromDate, toDate } = guestUser.guestAccessInfo;
      const { emailAddress, firstName, lastName } = guestUser.guestInfo;
      return {
        emailAddress,
        firstName,
        lastName,
        fromDate,
        toDate,
        personBeingVisited,
      } as GuestUserMongoose;
    } catch (error) {}
  }

  private async createGuestUserModel(
    guestUserMongoose: GuestUserMongoose,
  ): Promise<Model<GuestUserMongoose>> {
    try {
      return new this.guestUserModel(guestUserMongoose);
    } catch (error) {
      console.log(error);
    }
  }

  private generateGuestAccessInfo(): GuestAccessInfo {
    const toDate = moment()
      .add(this.VALID_DAYS, DAY)
      .format(MOMENT_FORMAT);
    const fromDate = moment().format(MOMENT_FORMAT);
    return {
      toDate,
      fromDate,
      location: LOCATION,
      validDays: this.VALID_DAYS + 1, // why + 1 day needed for ISE api??
    } as GuestAccessInfo;
  }

  private generateGuestInfo(
    firstName: string,
    surName: string,
    password: string,
    emailAddress: string,
  ): GuestInfo {
    const guestInfo: GuestInfo = {
      firstName,
      enabled: true, // TODO: check if this property is required
      password,
      lastName: surName,
      userName: emailAddress,
      emailAddress,
      // TODO: check generation Time property (autogenerated?)
    };
    return guestInfo;
  }

  private generateGuestUser(
    guestInfo: GuestInfo,
    personBeingVisited: string,
    reasonForVisit: string,
  ): GuestUser {
    const guestUser: GuestUser = {
      guestInfo,
      id: '11111', // TODO: implement ID generator (name, email,??)
      name: 'tesGuestUer', // TODO: check reasoning for name property, still needed?
      guestAccessInfo: this.generateGuestAccessInfo(),
      personBeingVisited,
      reasonForVisit,
      portalId: PORTAL_ID,
      guestType: GUEST_TYPE,
    };
    return guestUser;
  }
}
