import { Injectable } from '@nestjs/common';
import { IseService } from '../ise/ise.service';
import * as moment from 'moment';
import { CreateGuestUserDto } from 'src/models/CreateGuestUserDto.dto';
import { GuestInfo } from 'src/models/GuestInfo';
import { GuestUser } from 'src/models/GuestUser';
import { IseGuestUserDto } from 'src/models/IseGuestUserDto';
import { GuestAccessInfo } from 'src/models/GuestAccessInfo';
import { InjectModel } from '@nestjs/mongoose';
import { GuestUserMongoose } from 'src/models/GuestUserMongoose';
import { Model } from 'mongoose';

const LOCATION = 'Brussels';
const PORTAL_ID = 'f10871e0-7159-11e7-a355-005056aba474';
const GUEST_TYPE = 'Weekly (default)'; // TODO: check guest type
const MOMENT_FORMAT = 'MM/DD/YYYY HH:mm';
const DAY = 'day';

@Injectable()
export class GuestUserService {
  private VALID_DAYS: number;

  constructor(
    private iseService: IseService,
    @InjectModel('GuestUser') private guestUserModel: Model<GuestUserMongoose>,
  ) {
    this.VALID_DAYS = 2;
  }

  public async createGuestUser(createGuestUserDto: CreateGuestUserDto) {
    const {
      password,
      firstName,
      surName,
      emailAddress,
      personBeingVisited,
      reasonForVisit,
    } = createGuestUserDto;

    const guestInfo: GuestInfo = this.generateGuestInfo(
      firstName,
      surName,
      password,
      emailAddress,
    );
    const guestUser: GuestUser = this.generateGuestUser(
      guestInfo,
      personBeingVisited,
      reasonForVisit,
    );
    const iseGuestUserDto: IseGuestUserDto = {
      GuestUser: guestUser,
    };
    try {
    //  await this.iseService.createISEGuestUser(iseGuestUserDto);
      await this.saveGuestUserToMongodb(guestUser);
    } catch (error) {
      console.log(error);
      console.log(`could not create Ise guest user ${error}`);
    }
  }

  private async saveGuestUserToMongodb(guestUser: GuestUser) {
    const { personBeingVisited } = guestUser;
    const { fromDate, toDate } = guestUser.guestAccessInfo;
    const { emailAddress, firstName, lastName } = guestUser.guestInfo;
    const guestUserMongoose: GuestUserMongoose = {
      emailAddress,
      firstName,
      lastName,
      fromDate,
      toDate,
      personBeingVisited,
    };
    let createdGuestUser = new this.guestUserModel(guestUserMongoose);
    return await createdGuestUser.save();
  }

  private generateGuestAccessInfo(): GuestAccessInfo {
    const toDate = moment()
      .add(this.VALID_DAYS, DAY)
      .format(MOMENT_FORMAT);
    const fromDate = moment().format(MOMENT_FORMAT);
    return {
      toDate,
      fromDate,
      location: LOCATION,
      validDays: this.VALID_DAYS + 1, // why + 1 day needed for ISE api??
    } as GuestAccessInfo;
  }

  private generateGuestInfo(
    firstName: string,
    surName: string,
    password: string,
    emailAddress: string,
  ): GuestInfo {
    const guestInfo: GuestInfo = {
      firstName,
      enabled: true, // TODO: check if this property is required
      password,
      lastName: surName,
      userName: emailAddress,
      emailAddress,
      // TODO: check generation Time property (autogenerated?)
    };
    return guestInfo;
  }

  private generateGuestUser(
    guestInfo: GuestInfo,
    personBeingVisited: string,
    reasonForVisit: string,
  ): GuestUser {
    const guestUser: GuestUser = {
      guestInfo,
      id: '11111', // TODO: implement ID generator (name, email,??)
      name: 'tesGuestUer', // TODO: check reasoning for name property, still needed?
      guestAccessInfo: this.generateGuestAccessInfo(),
      personBeingVisited,
      reasonForVisit,
      portalId: PORTAL_ID,
      guestType: GUEST_TYPE,
    };
    return guestUser;
  }
}
